//
// Created by os on 9/5/23.
//

#ifndef PROJECT_BASE_REPOSITORY_PREDAJA_CONSOLE_HPP
#define PROJECT_BASE_REPOSITORY_PREDAJA_CONSOLE_HPP


class Console {

};


#endif //PROJECT_BASE_REPOSITORY_PREDAJA_CONSOLE_HPP
